<?xml version="1.0"?>
<!--
Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying 
documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, 
and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject 
to the following:

The copyright notices in the Software and this entire statement, including the above license grant, the original location it was 
downloaded from, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, 
and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object
code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. THE SOFTWARE MAY CONTAIN BUGS, ERRORS AND OTHER
PROBLEMS THAT COULD CAUSE SYSTEM FAILURES AND THE USE OF SUCH SOFTWARE IS ENTIRELY AT THE USER'S RISK. IN NO EVENT SHALL THE COPYRIGHT
HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

************************************************************************************************************************************
This file defines new UI elements that all workspaces will contain
************************************************************************************************************************************
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:frmwrk="Corel Framework Data">
  <xsl:output method="xml" encoding="UTF-8" indent="yes"/>

  <!-- Use these elements for the framework to move the container from the app config file to the user config file -->
  <!-- Since these elements use the frmwrk name space, they will not be executed when the XSLT is applied to the user config file -->
  <frmwrk:uiconfig>
    <!-- The Application Info should always be the topmost frmwrk element -->
    <frmwrk:applicationInfo userConfiguration="true" />
  </frmwrk:uiconfig>

  <!-- Copy everything -->
  <xsl:template match="node()|@*">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="uiConfig/items">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>

      <!-- Define the button which shows the docker -->
      <itemData guid="fa55bc80-fd19-4869-9188-d59bd5bcfc39" noBmpOnMenu="true"
                type="checkButton"
                check="*Docker('bc9bcaad-b5c3-4bd6-8ae3-726a02e2e9a4')"
                dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd"
                userCaption="BPYmergeTool"
                enable="true"/>

      <!-- Define the web control which will be placed on our docker -->
      <itemData guid="5878b3a1-39c8-41d6-ad63-7b9ebd1f0bcf"
                type="wpfhost"
                hostedType="Addons\BPYmergeTool\BPYmergeTool.dll,BPYmergeTool.DockerUI"
                enable="true"/>
		<itemData guid="9387393f-8a16-4ee5-9ef5-ef9f4f8eb5b9" flyoutBarRef="919643bf-a3a6-46b7-9544-8aebbf4263a3" type="flyout" userCreated="true" noBmpOnMenu="true" userToolTip="CdrPreflight" userCaption="Bophiyen"/>
		<itemData guid="df8e36f9-f0e4-4159-9df8-85addc5ddb6f" dynamicCommand="Addons\BPYmergeTool\BPYmergeTool.dll,BPYmergeTool.DockerUI.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="Tool menu" userToolTip="Try menu" noBmpOnMenu="true" />
		<itemData guid="8a63f39b-387e-4bf7-8c2c-569cd55aec0a" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="Apply Multiply" userToolTip="Apply Multiply" noBmpOnMenu="true" />
		<itemData guid="1229d19c-3b22-48bd-b319-6cfeb9aacd12" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="To Curve" userToolTip="Select Text To Curve" noBmpOnMenu="true" />
		<itemData guid="6d66ee9e-e688-46c2-85da-407dc7488a0a" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="Fit Frame To Content" userToolTip="Fit Frame To Content" noBmpOnMenu="true" />
		<itemData guid="55d10d22-0b9d-4fe6-b5d5-72722bc3d3ed" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="Guideline From Nodes" userToolTip="Create Guideline From Nodes" noBmpOnMenu="true" />
		<itemData guid="5693b702-da98-4530-8f14-3c47d1aa0b0b" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="ToBit3" userToolTip="Convert to Bitmap #3" noBmpOnMenu="true" />
		<itemData guid="a14ed599-6906-4f15-be2d-c4c9261c1797" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="ToBit2" userToolTip="Convert to Bitmap #2" noBmpOnMenu="true" />
		<itemData guid="79864acc-751c-4e5f-a69b-00014802144e" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="ToBit1" userToolTip="Convert to Bitmap #1" noBmpOnMenu="true" />
		<itemData guid="a8bd06bb-41a0-469b-a578-369388844f68" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="ToBit Settings" userToolTip="Convert to Bitmap Settings" noBmpOnMenu="true" />
		<itemData guid="efc9b3a2-1f91-49b1-aea0-1bc6d788114e" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="Guideline From Node and Angle" userToolTip="Create Guideline From Node &amp; Angle" noBmpOnMenu="true" />
		<itemData guid="ab84bbcb-18de-4b19-be6c-c560a66bbbad" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="Create Guideline From Node V/H" userToolTip="Create Guideline From Node (Vertical/Horisontal)" noBmpOnMenu="true" />
		<itemData guid="d35d5e36-e36e-4b49-b6d1-382df9dbd040" dynamicCommand="GlobalMacros.ThisMacroStorage.hellow" dynamicCategory="2cc24a3e-fe24-4708-9a74-9c75406eebcd" userCaption="From Node and Rotate Center" userToolTip="Create Guideline From Node &amp; Rotate Center" noBmpOnMenu="true" />
    </xsl:copy>
  </xsl:template>
	<xsl:template match="uiConfig/commandBars">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>
			<commandBarData guid="919643bf-a3a6-46b7-9544-8aebbf4263a3" type="menu" nonLocalizableName="Bophiyen" flyout="true">
				<menu>
					<item guidRef="df8e36f9-f0e4-4159-9df8-85addc5ddb6f"/>
					<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400"/>
					<!-- -->
					<item guidRef="1229d19c-3b22-48bd-b319-6cfeb9aacd12"/>
					<item guidRef="6d66ee9e-e688-46c2-85da-407dc7488a0a"/>
					<item guidRef="8a63f39b-387e-4bf7-8c2c-569cd55aec0a"/>
					<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400"/>
					<!-- -->
					<item guidRef="79864acc-751c-4e5f-a69b-00014802144e"/>
					<item guidRef="5693b702-da98-4530-8f14-3c47d1aa0b0b"/>
					<item guidRef="a14ed599-6906-4f15-be2d-c4c9261c1797"/>
					<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400"/>
					<!-- -->
					<item guidRef="a8bd06bb-41a0-469b-a578-369388844f68"/>
					<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400"/>
					<!-- -->
					<item guidRef="55d10d22-0b9d-4fe6-b5d5-72722bc3d3ed"/>
					<item guidRef="efc9b3a2-1f91-49b1-aea0-1bc6d788114e"/>
					<item guidRef="ab84bbcb-18de-4b19-be6c-c560a66bbbad"/>
					<item guidRef="d35d5e36-e36e-4b49-b6d1-382df9dbd040"/>
					<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400"/>
					<!-- -->
				</menu>
			</commandBarData>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="/uiConfig/customizationList/container/modeData[@guid='7aa80134-8e64-42d1-be0a-c7ec7f6c441f']">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>
			<item guidRef="9387393f-8a16-4ee5-9ef5-ef9f4f8eb5b9"/>
			<item guidRef="df8e36f9-f0e4-4159-9df8-85addc5ddb6f"/>
			<item guidRef="8a63f39b-387e-4bf7-8c2c-569cd55aec0a"/>
			<item guidRef="1229d19c-3b22-48bd-b319-6cfeb9aacd12"/>
			<item guidRef="6d66ee9e-e688-46c2-85da-407dc7488a0a"/>
			<item guidRef="79864acc-751c-4e5f-a69b-00014802144e"/>
			<item guidRef="a14ed599-6906-4f15-be2d-c4c9261c1797"/>
			<item guidRef="5693b702-da98-4530-8f14-3c47d1aa0b0b"/>
			<item guidRef="a8bd06bb-41a0-469b-a578-369388844f68"/>
			<item guidRef="55d10d22-0b9d-4fe6-b5d5-72722bc3d3ed"/>
			<item guidRef="efc9b3a2-1f91-49b1-aea0-1bc6d788114e"/>
			<item guidRef="ab84bbcb-18de-4b19-be6c-c560a66bbbad"/>
			<item guidRef="d35d5e36-e36e-4b49-b6d1-382df9dbd040"/>
		</xsl:copy>
	</xsl:template>
  <xsl:template match="uiConfig/dockers">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>

      <!-- Define the web docker -->
      <dockerData guid="bc9bcaad-b5c3-4bd6-8ae3-726a02e2e9a4"
                  userCaption="BPYmergeTool"
                  wantReturn="true"
                  focusStyle="noThrow">
        <container>
          <!-- add the webpage control to the docker -->
          <item dock="fill" margin="0,0,0,0" guidRef="5878b3a1-39c8-41d6-ad63-7b9ebd1f0bcf"/>
        </container>
      </dockerData>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>
